export const countries = [
  "Afeganistão",
  "Ilhas Aland",
  "Albânia",
  "Argélia",
  "Samoa Americana",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antártica",
  "Antigua e Barbuda",
  "Argentina",
  "Armênia",
  "Aruba",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Bielo-Rússia",
  "Bélgica",
  "Belize",
  "Benin",
  "Bermudas",
  "Butão",
  "Bolívia",
  "Bonaire, Sint Eustatius e Saba",
  "Bósnia e Herzegovina",
  "Botswana",
  "Ilha Bouvet",
  "Brasil",
  "Território Britânico do Oceano Índico",
  "Brunei Darussalam",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Camboja",
  "Camarões",
  "Canadá",
  "cabo Verde",
  "Ilhas Cayman",
  "República Centro-Africana",
  "Chade",
  "Chile",
  "China",
  "Ilha do Natal",
  "Ilhas Cocos (Keeling)",
  "Colômbia",
  "Comores",
  "Congo",
  "Congo, República Democrática do Congo",
  "Ilhas Cook",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croácia",
  "Cuba",
  "Curaçao",
  "Chipre",
  "República Checa",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "República Dominicana",
  "Equador",
  "Egito",
  "El Salvador",
  "Guiné Equatorial",
  "Eritreia",
  "Estônia",
  "Etiópia",
  "Ilhas Falkland (Malvinas)",
  "ilhas Faroe",
  "Fiji",
  "Finlândia",
  "França",
  "Guiana Francesa",
  "Polinésia Francesa",
  "Territórios Franceses do Sul",
  "Gabão",
  "Gâmbia",
  "Georgia",
  "Alemanha",
  "Gana",
  "Gibraltar",
  "Grécia",
  "Groenlândia",
  "Grenada",
  "Guadalupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guiné",
  "Guinea-bissau",
  "Guiana",
  "Haiti",
  "Ilha Heard e Ilhas McDonald",
  "Santa Sé (Estado da Cidade do Vaticano)",
  "Honduras",
  "Hong Kong",
  "Hungria",
  "Islândia",
  "Índia",
  "Indonésia",
  "Irã (Republic Islâmica do Irã",
  "Iraque",
  "Irlanda",
  "Ilha de Man",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jersey",
  "Jordânia",
  "Cazaquistão",
  "Quênia",
  "Kiribati",
  "Coréia, República Popular Democrática da",
  "Republica da Coréia",
  "Kosovo",
  "Kuwait",
  "Quirguistão",
  "República Democrática Popular do Laos",
  "Letônia",
  "Líbano",
  "Lesoto",
  "Libéria",
  "Jamahiriya Árabe da Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macau",
  "Macedônia, Antiga República Iugoslava da",
  "Madagáscar",
  "Malawi",
  "Malásia",
  "Maldivas",
  "Mali",
  "Malta",
  "Ilhas Marshall",
  "Martinica",
  "Mauritânia",
  "Maurício",
  "Mayotte",
  "México",
  "Micronésia, Estados Federados da",
  "Moldávia, República da",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Montserrat",
  "Marrocos",
  "Moçambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Países Baixos",
  "Antilhas Holandesas",
  "Nova Caledônia",
  "Nova Zelândia",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Niue",
  "Ilha Norfolk",
  "Ilhas Marianas do Norte",
  "Noruega",
  "Omã",
  "Paquistão",
  "Palau",
  "Território Palestino, Ocupado",
  "Panamá",
  "Papua Nova Guiné",
  "Paraguai",
  "Filipinas",
  "Pitcairn",
  "Polônia",
  "Portugal",
  "Porto Rico",
  "Catar",
  "Reunião",
  "Romênia",
  "Federação Russa",
  "Ruanda",
  "São Bartolomeu",
  "Santa Helena",
  "São Cristóvão e Neves",
  "Santa Lúcia",
  "são Martinho",
  "São Pedro e Miquelão",
  "São Vicente e Granadinas",
  "Samoa",
  "San Marino",
  "São Tomé e Príncipe",
  "Arábia Saudita",
  "Senegal",
  "Sérvia",
  "Sérvia e Montenegro",
  "Seychelles",
  "Serra Leoa",
  "Cingapura",
  "St Martin",
  "Eslováquia",
  "Eslovênia",
  "Ilhas Salomão",
  "Somália",
  "África do Sul",
  "Geórgia do Sul e Ilhas Sandwich do Sul",
  "Sudão do Sul",
  "Espanha",
  "Sri Lanka",
  "Sudão",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Suazilândia",
  "Suécia",
  "Suíça",
  "República Árabe da Síria",
  "Taiwan, província da China",
  "Tajiquistão",
  "Tanzânia, República Unida da",
  "Tailândia",
  "Timor-Leste",
  "Ir",
  "Tokelau",
  "Tonga",
  "Trinidad e Tobago",
  "Tunísia",
  "Peru",
  "Turcomenistão",
  "Ilhas Turcas e Caicos",
  "Tuvalu",
  "Uganda",
  "Ucrânia",
  "Emirados Árabes Unidos",
  "Reino Unido",
  "Estados Unidos",
  "Ilhas Menores Distantes dos Estados Unidos",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Ilhas Virgens Britânicas",
  "Ilhas Virgens, EUA",
  "Wallis e Futuna",
  "Saara Ocidental",
  "Iémen",
  "Zâmbia",
  "Zimbábue",
];
